name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        go-version: [ 1.13.x ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag txs-processor:$(date +%s)
    - name: run tests
      run: go test -json ./... > test.json
    - name: Annotate tests
      if: always()
      uses: guyarb/golang-test-annoations@v0.3.0
      with:
        test-results: test.json
        package-name: foobar # optional, if using custom package name, github.com/owner/repo stripped from the pathname by default
    - name: GitHub Action for DigitalOcean - doctl
      # You may pin to the exact commit or the version.
      # uses: digitalocean/action-doctl@7f3a9967e5f7b8f4581cf10e6891535614f36850
      uses: digitalocean/action-doctl@v2.1.0
      with:
        # Version of doctl to install
#         version: # optional, default is latest
        # DigitalOcean API Token
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    # Build docker image and publish
    - name: DigitalOcean Docker Image Publish
      # You may pin to the exact commit or the version.
      # uses: ripplr-io/docr-docker-publish@4b4d57000d6e16fe589b3cea2d491830b9d7da87
      uses: ripplr-io/docr-docker-publish@v1
      with:
        # Image path in the format registry-name/image-name
        image_path: ${{ secrets.IMAGE_PATH }}
        # Number of characters from the commit SHA
        sha_size: 8 # optional, default is 8
    - name: Notify Telegram
      uses: yanzay/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.chat }} # user id or channel name secret
        token: ${{ secrets.token }} # token secret
        status: ${{ job.status }} # do not modify this line  
